Create application settings
indiebox/equality-desktop pull request #90
Opened 2022-06-03 10:14 UTC by RedMarshall37

2022-06-07 10:01 UTC, igorgaming requested changes

2022-06-07 10:01 UTC, igorgaming commented on Equality/Views/Teams/TeamPage.xaml
> +        <Style BasedOn="{StaticResource MaterialDesignTabRadioButton}"
I believe you define this style in 2+ places, so move this in resource dictionary for all application (`Themes/Buttons`)

2022-06-17 09:28 UTC, RedMarshall37 commented on Equality/Services/ThemeService.cs
> +        delegate void SyncTheme();
No. We need to remove this?

2022-06-17 09:35 UTC, igorgaming commented on Equality/Services/ThemeService.cs
> +        delegate void SyncTheme();
Sure

2022-06-17 09:53 UTC, RedMarshall37 commented on Equality/Services/ThemeService.cs
> +        delegate void SyncTheme();
i am wrong. We use it here
![image](https://user-images.githubusercontent.com/81381851/174274895-a41fe2bc-5d2d-40d6-a645-90b52352291b.png)
And here
<img width="677" alt="image" src="https://user-images.githubusercontent.com/81381851/174275002-b1bc03b7-f1d8-4662-8110-9b4af8d355ca.png">

2022-07-30 12:19 UTC, merged